import asyncio
import aiohttp
import os
import time
import random

G = "\033[92m"
R = "\033[91m"
W = "\033[0m"
CY = "\033[96m"

USER_AGENTS = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 17_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0'
]

async def verificar_site(session, nome, url_base, username, encontrados, sem):
    url_alvo = url_base.format(username)
    headers = {'User-Agent': random.choice(USER_AGENTS)}
    
    falsos_positivos = [
        "not found", "não encontrado", "página não encontrada", 
        "does not exist", "page not found", "error 404", 
        "this page doesn't exist", "perfil não existe",
        "could not be found", "0 results", "no results",
        "ninguém com esse nome", "user not found",
        "hasn't set up a profile", "account suspended", "suspended",
        "page unavailable", "não está disponível", "não há resultados",
        "nenhum usuário", "nenhum resultado", "nobody here"
    ]
    
    async with sem:
        try:
            async with session.get(url_alvo, headers=headers, timeout=5, allow_redirects=True) as res:
                url_final = str(res.url).rstrip('/')
                url_alvo_limpa = url_alvo.rstrip('/')
                
                redirecionamento_falso = False
                if url_final != url_alvo_limpa:
                    if "login" in url_final.lower() or "auth" in url_final.lower() or "error" in url_final.lower():
                        redirecionamento_falso = True
                    elif url_final == url_base.split("/{}")[0].rstrip('/'):
                        redirecionamento_falso = True

                if res.status == 200 and not redirecionamento_falso:
                    corpo = await res.text()
                    corpo_lower = corpo.lower()
                    
                    if username.lower() in corpo_lower:
                        is_falso_positivo = any(fp in corpo_lower for fp in falsos_positivos)
                        
                        if not is_falso_positivo:
                            print(f"{G}[+] {nome:20} -> {url_alvo}{W}")
                            encontrados.append(url_alvo)
        except:
            pass

async def main():
    banco_osint = {
        "Instagram": "https://www.instagram.com/{}",
        "TikTok": "https://www.tiktok.com/@{}",
        "Twitter/X": "https://twitter.com/{}",
        "Facebook": "https://www.facebook.com/{}",
        "Pinterest": "https://www.pinterest.com/{}",
        "Reddit": "https://www.reddit.com/user/{}",
        "Snapchat": "https://www.snapchat.com/add/{}",
        "Telegram": "https://t.me/{}",
        "YouTube": "https://www.youtube.com/@{}",
        "Twitch": "https://www.twitch.tv/{}",
        "Roblox": "https://www.roblox.com/user.aspx?username={}",
        "Steam": "https://steamcommunity.com/id/{}",
        "GitHub": "https://github.com/{}",
        "Linktree": "https://linktr.ee/{}",
        "DefacerId": "https://defacer.id/{}",
        "Behance": "https://www.behance.net/{}",
        "Medium": "https://medium.com/@{}",
        "Kaggle": "https://www.kaggle.com/{}",
        "NameMC (Minecraft)": "https://pt.namemc.com/profile/{}",
        "Speedrun.com": "https://www.speedrun.com/users/{}",
        "NexusMods": "https://www.nexusmods.com/users/{}",
        "Top.gg (Discord)": "https://top.gg/user/{}",
        "Osu!": "https://osu.ppy.sh/users/{}",
        "Tracker.gg (Valorant/Fortnite)": "https://tracker.gg/valorant/profile/riot/{}/overview",
        "Chess.com": "https://www.chess.com/member/{}",
        "RecRoom": "https://rec.net/user/{}",
        "Riot Games (OP.GG)": "https://www.op.gg/summoners/br/{}",
        "Vercel": "https://vercel.com/{}",
        "Replit": "https://replit.com/@{}",
        "CodePen": "https://codepen.io/{}",
        "DockerHub": "https://hub.docker.com/u/{}",
        "Dribbble": "https://dribbble.com/{}",
        "PyPi (Python Packages)": "https://pypi.org/user/{}",
        "PCPartPicker": "https://pcpartpicker.com/user/{}",
        "GameJolt": "https://gamejolt.com/@{}",
        "Itch.io": "https://{}.itch.io/",
        "GOG (Good Old Games)": "https://www.gog.com/u/{}",
        "Adobe Portfolio": "https://{}.myportfolio.com/",
        "Canva (Design)": "https://www.canva.com/{}",
        "ArtStation": "https://www.artstation.com/{}",
        "Figma": "https://www.figma.com/@{}",
        "99Designs": "https://99designs.com/profiles/{}",
        "Contently": "https://{}.contently.com/",
        "Enjoei": "https://www.enjoei.com.br/@{}",
        "Vrum": "https://www.vrum.com.br/perfil/{}",
        "Tabela FIPE (Perfil)": "https://www.tabelafipe.com.br/usuario/{}",
        "Skoob": "https://www.skoob.com.br/usuario/{}",
        "Jusbrasil": "https://www.jusbrasil.com.br/perfil/{}",
        "Escavador": "https://www.escavador.com/sobre/{}",
        "LucidChart": "https://lucid.app/users/{}",
        "Gumroad": "https://gumroad.com/{}",
        "BuyMeACoffee": "https://www.buymeacoffee.com/{}",
        "OpenSea (NFT)": "https://opensea.io/{}",
        "Rarible": "https://rarible.com/{}",
        "OLX": "https://www.olx.com.br/perfil/{}",
        "Koo App": "https://www.kooapp.com/profile/{}",
        "Tabnews": "https://www.tabnews.com.br/{}",
        "DeHashed": "https://dehashed.com/search?query={}",
        "LeakCheck": "https://leakcheck.io/user/{}",
        "IntelX": "https://intelx.io/?s={}",
        "Alvanista": "http://alvanista.com/{}",
        "RetroAchievements": "https://retroachievements.org/user/{}",
        "Lichess": "https://lichess.org/@/{}",
        "Casas Bahia (Perfil)": "https://www.casasbahia.com.br/perfil/{}",
        "Extra (Perfil)": "https://www.extra.com.br/perfil/{}",
        "Ponto Frio (Perfil)": "https://www.pontofrio.com.br/perfil/{}",
        "Estante Virtual": "https://www.estantevirtual.com.br/usuario/{}",
        "Flogão (Novo)": "https://flogao.com.br/{}",
        "CifraClub": "https://www.cifraclub.com.br/perfil/{}",
        "PalcoMP3": "https://www.palcomp3.com.br/{}",
        "HuggingFace": "https://huggingface.co/{}",
        "Railway.app": "https://railway.app/u/{}",
        "Supabase": "https://supabase.com/dashboard/profile/{}",
        "Glitch.com": "https://glitch.com/@{}",
        "Postman": "https://www.postman.com/{}",
        "Observable": "https://observablehq.com/@{}",
        "CurseForge": "https://www.curseforge.com/members/{}/projects",
        "ModDB": "https://www.moddb.com/members/{}",
        "SkinDex (Minecraft)": "https://www.minecraftskins.com/profile/{}",
        "PlanetMinecraft": "https://www.planetminecraft.com/member/{}",
        "GameBanana": "https://gamebanana.com/members/{}",
        "Eldorado.gg": "https://www.eldorado.gg/users/{}",
        "Carrd.co": "https://{}.carrd.co/",
        "Bio.link": "https://bio.link/{}",
        "AllMyLinks": "https://allmylinks.com/{}",
        "Solo.to": "https://solo.to/{}",
        "Taplink": "https://taplink.cc/{}",
        "Teletype.in": "https://teletype.in/@{}",
        "Ko-fi": "https://ko-fi.com/{}",
        "Substack (Alt)": "https://{}.substack.com/",
        "Ghost.org": "https://{}.ghost.io/",
        "Write.as": "https://write.as/{}",
        "Hashnode (Alt)": "https://{}.hashnode.dev/",
        "DeviantArt (Alt)": "https://www.deviantart.com/{}",
        "Flickr": "https://www.flickr.com/photos/{}",
        "Cloudflare Pages": "https://{}.pages.dev",
        "Netlify": "https://{}.netlify.app",
        "Azure (Static Apps)": "https://{}.azurestaticapps.net",
        "Heroku": "https://{}.herokuapp.com",
        "Firebase (App)": "https://{}.firebaseapp.com",
        "Fly.io": "https://{}.fly.dev",
        "Game-Monitor": "https://www.game-monitor.com/user/{}",
        "Speclist": "https://speclist.com/{}",
        "R6Stats": "https://r6stats.com/stats/{}",
        "OP.GG (Global)": "https://www.op.gg/summoners/na/{}",
        "LeagueOfGraphs": "https://www.leagueofgraphs.com/summoner/br/{}",
        "Carbonmade": "https://{}.carbonmade.com/",
        "Clippings.me": "https://www.clippings.me/{}",
        "Crevado": "https://{}.crevado.com/",
        "JournalPortfólio": "https://{}.journalportfólio.com/",
        "Portfolio.io": "https://portfolio.io/{}",
        "MySpace": "https://myspace.com/{}",
        "Zhihu": "https://www.zhihu.com/people/{}",
        "OkCupid": "https://www.okcupid.com/profile/{}",
        "Couchsurfing": "https://www.couchsurfing.com/people/{}",
        "Badoo (Perfil Público)": "https://badoo.com/profile/{}",
        "Vakinha": "https://www.vakinha.com.br/perfil/{}",
        "Apoia.se": "https://apoia.se/{}",
        "Catarse": "https://www.catarse.me/{}",
        "Parafernalha": "https://www.parafernalha.com.br/{}",
        "Kwak (BR)": "https://kwak.com.br/{}",
        "Nuuvem (Games BR)": "https://www.nuuvem.com/perfil/{}",
        "Lnk.bio": "https://lnk.bio/{}",
        "Campsite.bio": "https://campsite.bio/{}",
        "ContactInBio": "https://{}.contactinbio.com",
        "Shorby": "https://shor.by/{}",
        "Koji": "https://withkoji.com/@{}",
        "Canny.io": "https://{}.canny.io",
        "FOSSTodon": "https://fosstodon.org/@{}",
        "Chaos.social": "https://chaos.social/@{}",
        "Mastodon.social": "https://mastodon.social/@{}",
        "Keybase.io": "https://keybase.io/{}",
        "Elo7 (Perfil)": "https://www.elo7.com.br/{}",
        "Zoom (Buscapé)": "https://www.zoom.com.br/perfil/{}",
        "Abilio (Games)": "https://{}.abilio.com.br",
        "Pichau (Comentários)": "https://www.pichau.com.br/perfil/{}",
        "SlideShare": "https://www.slideshare.net/{}",
        "SpeakerDeck": "https://speakerdeck.com/{}",
        "Issuu": "https://issuu.com/{}",
        "Scribd": "https://www.scribd.com/user/{}",
        "Patreon (Alt)": "https://www.patreon.com/{}",
        "LinkPop": "https://linkpop.com/{}",
        "Tellonym": "https://tellonym.me/{}",
        "CuriousCat": "https://curiouscat.live/{}",
        "Ask.fm": "https://ask.fm/{}",
        "500px": "https://500px.com/p/{}",
        "VSCO": "https://vsco.co/{}",
        "ViewBug": "https://www.viewbug.com/member/{}",
        "EyeEm": "https://www.eyeem.com/u/{}",
        "Gurushots": "https://gurushots.com/{}/photos",
        "Polywork": "https://www.polywork.com/{}",
        "Read.cv": "https://read.cv/{}",
        "Contra": "https://contra.com/{}",
        "Wellfound (AngelList)": "https://wellfound.com/u/{}",
        "Zotero (Acadêmico)": "https://www.zotero.org/{}",
        "Untappd (Cervejas)": "https://untappd.com/user/{}",
        "Vivino (Vinhos)": "https://www.vivino.com/users/{}",
        "Discogs (Vinil/Música)": "https://www.discogs.com/user/{}",
        "BoardGameGeek": "https://boardgamegeek.com/user/{}",
        "AllTrails": "https://www.alltrails.com/members/{}",
        "Zapper.fi": "https://zapper.fi/bundle/{}",
        "DeBank": "https://debank.com/profile/{}",
        "Lens Protocol": "https://lens.xyz/u/{}",
        "Mirror.xyz": "https://mirror.xyz/{}",
        "Kvak (Social BR)": "https://kwak.com.br/{}",
        "Recanto das Letras": "https://www.recantodasletras.com.br/autor.php?id={}",
        "Vimeo (Direct)": "https://vimeo.com/{}",
        "Dailymotion (User)": "https://www.dailymotion.com/{}",
        "Twitch (Alternative)": "https://passport.twitch.tv/users/{}",
        "Buscapé (Perfil)": "https://www.buscape.com.br/perfil/{}",
        "Pelando (Promoções)": "https://www.pelando.com.br/profile/{}",
        "Promobit": "https://www.promobit.com.br/perfil/{}",
        "Meliuz": "https://www.meliuz.com.br/perfil/{}",
        "GetNinjas": "https://www.getninjas.com.br/anuncios/{}",
        "Superprof (BR)": "https://www.superprof.com.br/{}",
        "Sympla (Eventos)": "https://www.sympla.com.br/produtor/{}",
        "Zora.co": "https://zora.co/{}",
        "ENS (Ethereum Name)": "https://app.ens.domains/{}",
        "Instant Gaming": "https://www.instant-gaming.com/user/{}",
        "Eneba": "https://www.eneba.com/user/{}",
        "VRChat": "https://vrchat.com/home/user/{}",
        "Fotolog (Archive)": "https://fotolog.com/{}",
        "Last.fm": "https://www.last.fm/user/{}",
        "Letterboxd": "https://letterboxd.com/{}",
        "Goodreads (Direct)": "https://www.goodreads.com/{}",
        "Wixsite (Subdomain)": "https://{}.wixsite.com",
        "Gitbook": "https://{}.gitbook.io",
        "Bento.me": "https://bento.me/{}",
        "Linkfree": "https://linkfree.io/{}",
        "About.me": "https://about.me/{}",
        "Gravatar": "https://en.gravatar.com/{}",
        "LinkStack": "https://linkstack.org/{}",
        "Vagalume (Música BR)": "https://www.vagalume.com.br/{}/",
        "Rate Your Music": "https://rateyourmusic.com/~{}",
        "Mixcloud": "https://www.mixcloud.com/{}/",
        "Bandcamp": "https://bandcamp.com/{}",
        "Trakt.tv (Séries)": "https://trakt.tv/users/{}",
        "TV Time": "https://www.tvtime.com/en/user/{}",
        "AniList": "https://anilist.co/user/{}/",
        "Kitsu (Anime)": "https://kitsu.io/users/{}",
        "MyAnimeList": "https://myanimelist.net/profile/{}",
        "Hacker News": "https://news.ycombinator.com/user?id={}",
        "Lobsters": "https://lobste.rs/u/{}",
        "Hackernoon": "https://hackernoon.com/u/{}",
        "VirusTotal": "https://www.virustotal.com/gui/user/{}",
        "Packet Storm": "https://packetstormsecurity.com/search/authors/?q={}",
        "Exploit-DB": "https://www.exploit-db.com/author/{}",
        "Bitbucket": "https://bitbucket.org/{}/",
        "SourceForge": "https://sourceforge.net/u/{}",
        "FreeCodeCamp": "https://www.freecodecamp.org/{}",
        "Codewars": "https://www.codewars.com/users/{}",
        "Pexels": "https://www.pexels.com/@{}",
        "Pixabay": "https://pixabay.com/users/{}",
        "Unsplash": "https://unsplash.com/@{}",
        "Instructables (DIY)": "https://www.instructables.com/member/{}",
        "WikiHow (User)": "https://www.wikihow.com/User:{}",
        "Steam Ladder": "https://steamladder.com/profile/{}",
        "HowLongToBeat": "https://howlongtobeat.com/user/{}",
        "Taringa (Social LatAm)": "https://www.taringa.net/{}/",
        "Reclame Aqui (Usuário)": "https://www.reclameaqui.com.br/p/{}/",
        "Infojobs (Perfil BR)": "https://www.infojobs.com.br/{}",
        "OpenStreetMap": "https://www.openstreetmap.org/user/{}",
        "Product Hunt": "https://www.producthunt.com/@{}",
        "BeerAdvocate": "https://www.beeradvocate.com/community/members/{}",
        "TripIt (Viagens)": "https://www.tripit.com/people/{}/profile",
        "Foursquare (Swarm)": "https://foursquare.com/user/{}",
        "WakaTime": "https://wakatime.com/@{}",
        "LeetCode": "https://leetcode.com/{}/",
        "Codecademy": "https://www.codecademy.com/profiles/{}",
        "Exercism": "https://exercism.org/profiles/{}",
        "Khan Academy": "https://www.khanacademy.org/profile/{}",
        "Scrimba": "https://scrimba.com/@{}",
        "Coursera": "https://www.coursera.org/user/{}",
        "Udemy (Perfil)": "https://www.udemy.com/user/{}/",
        "HackerOne": "https://hackerone.com/{}",
        "Bugcrowd": "https://bugcrowd.com/{}",
        "PentesterLab": "https://pentesterlab.com/profile/{}",
        "CTFlearn": "https://ctflearn.com/user/{}",
        "Codeberg": "https://codeberg.org/{}",
        "StackOverflow": "https://stackoverflow.com/users/{}",
        "Launchpad": "https://launchpad.net/~{}",
        "AUR (Arch Linux)": "https://aur.archlinux.org/users/{}",
        "Snapcraft": "https://snapcraft.io/publisher/{}",
        "OpenCollective": "https://opencollective.com/{}",
        "Imgur": "https://imgur.com/user/{}",
        "Giphy": "https://giphy.com/{}",
        "Archive.org": "https://archive.org/details/@{}",
        "WordPress (Blog)": "https://{}.wordpress.com",
        "Tumblr (Blog)": "https://{}.tumblr.com",
        "LiveJournal": "https://{}.livejournal.com",
        "Blogger": "https://{}.blogspot.com",
        "Quora (Perfil)": "https://www.quora.com/profile/{}",
        "Ebay": "https://www.ebay.com/usr/{}",
        "Etsy": "https://www.etsy.com/people/{}",
        "Trustpilot": "https://www.trustpilot.com/users/{}",
        "TripAdvisor": "https://www.tripadvisor.com/members/{}",
        "IFTTT": "https://ifttt.com/p/{}",
        "Domestika": "https://www.domestika.org/pt/{}",
        "NPM (JS)": "https://www.npmjs.com/~{}",
        "RubyGems (Ruby)": "https://rubygems.org/profiles/{}",
        "Packagist (PHP)": "https://packagist.org/users/{}/",
        "Crates.io (Rust)": "https://crates.io/users/{}",
        "Gitee (China)": "https://gitee.com/{}",
        "GitLab (Direct)": "https://gitlab.com/{}",
        "VK (Rússia)": "https://vk.com/{}",
        "Truth Social": "https://truthsocial.com/@{}",
        "Rumble": "https://rumble.com/user/{}",
        "TradingView": "https://www.tradingview.com/u/{}/",
        "Strava": "https://www.strava.com/athletes/{}",
        "MeWe": "https://mewe.com/i/{}",
        "Plurk": "https://www.plurk.com/{}",
        "BitChute": "https://www.bitchute.com/channel/{}/",
        "DLive": "https://dlive.tv/{}",
        "Trovo": "https://trovo.live/s/{}",
        "Picarto": "https://picarto.tv/{}",
        "Fandom": "https://www.fandom.com/u/{}",
        "Giant Bomb": "https://www.giantbomb.com/profile/{}/",
        "Metacritic": "https://www.metacritic.com/user/{}",
        "Backloggd": "https://www.backloggd.com/u/{}/",
        "Newgrounds": "https://{}.newgrounds.com",
        "Gaia Online": "https://www.gaiaonline.com/profiles/{}",
        "Kongregate": "https://www.kongregate.com/accounts/{}",
        "Sketchfab (3D)": "https://sketchfab.com/{}",
        "Thingiverse (3D)": "https://www.thingiverse.com/{}/about",
        "Mod.io": "https://mod.io/members/{}",
        "Wikipedia": "https://www.wikipedia.org/wiki/User:{}",
        "Willow": "https://wlo.link/@{}",
        "Pizazz": "https://pizazz.me/{}",
        "7cups": "https://www.7cups.com/@{}",
        "8tracks": "https://8tracks.com/{}",
        "Coggle": "https://coggle.it/@{}",
        "Flipboard": "https://flipboard.com/@{}",
        "Wattpad": "https://www.wattpad.com/user/{}",
        "Letras.mus.br": "https://www.letras.mus.br/perfil/{}/",
        "Cifras.com.br": "https://www.cifras.com.br/perfil/{}",
        "UnknownCheats": "https://www.unknowncheats.me/forum/members/{}.html",
        "ElitePvPers": "https://www.elitepvpers.com/forum/members/{}.html",
        "MPGH": "https://www.mpgh.net/forum/member.php?username={}",
        "Se7enSins": "https://www.se7ensins.com/members/{}/",
        "GBAtemp (Modding)": "https://gbatemp.net/members/{}/",
        "MinecraftForum": "https://www.minecraftforum.net/members/{}",
        "GameVicio (Fórum)": "https://forum.gamevicio.com/membros/{}/",
        "TibiaBR": "https://forums.tibiabr.com/members/{}",
        "Outerspace (Fórum BR)": "https://forum.outerspace.com.br/index.php?members/{}/",
        "IGN Boards": "https://www.ignboards.com/members/{}/",
        "NeoGAF": "https://www.neogaf.com/members/{}/",
        "ResetEra": "https://www.resetera.com/members/{}/",
        "NexusMods (Fórum)": "https://forums.nexusmods.com/index.php?/user/{}-/",
        "XDA Developers": "https://forum.xda-developers.com/m/{}/",
        "Guia do Hardware (BR)": "https://www.hardware.com.br/comunidade/members/{}/",
        "BlackHatWorld": "https://www.blackhatworld.com/members/{}/",
        "MalwareTips": "https://malwaretips.com/members/{}/",
        "BleepingComputer": "https://www.bleepingcomputer.com/forums/u/{}/",
        "WildersSecurity": "https://www.wilderssecurity.com/members/{}/",
        "Linus Tech Tips": "https://linustechtips.com/profile/{}-/",
        "MacRumors": "https://forums.macrumors.com/members/{}/",
        "AVForums": "https://www.avforums.com/members/{}/",
        "CrunchBang (Linux)": "https://forums.bunsenlabs.org/profile.php?id={}",
        "Arch Linux Forums": "https://bbs.archlinux.org/profile.php?id={}",
        "SkyscraperCity": "https://www.skyscrapercity.com/members/{}/",
        "Bodybuilding.com": "https://bodyspace.bodybuilding.com/about-me/{}",
        "FlyerTalk": "https://www.flyertalk.com/forum/members/{}.html",
        "VouDeMoto (BR)": "https://www.voudemoto.com.br/members/{}/",
        "Hardmob (BR)": "https://www.hardmob.com.br/members/{}.html",
        "Adrenaline (BR)": "https://forum.adrenaline.com.br/membros/{}/",
        "Clube do Hardware": "https://www.clubedohardware.com.br/profile/{}/",
        "Kiwifarms": "https://kiwifarms.st/members/{}/",
        "Mumsnet": "https://www.mumsnet.com/Talk/profile/{}",
        "StudentRoom": "https://www.thestudentroom.co.uk/member.php?u={}",
        "Snusbase": "https://snusbase.com/search?q={}",
        "Leak-Lookup": "https://leak-lookup.com/search/{}",
        "HaveIBeenPwned (Fórum)": "https://haveibeenpwned.com/unifiedsearch/{}",
        "HackForums": "https://hackforums.net/member.php?action=profile&username={}",
        "Nulled.to": "https://www.nulled.to/User-{}",
        "Cracked.io": "https://cracked.io/User-{}",
        "Sinister.ly": "https://sinister.ly/User-{}",
        "DemonForums": "https://demonforums.net/User-{}",
        "Altenen (Carding)": "https://altenen.is/members/{}/",
        "Exploit.in (Fórum)": "https://forum.exploit.in/profile/{}/", 
        "Crdpro": "https://crdpro.cc/members/{}/",
        "JustPaste.it": "https://justpaste.it/u/{}",
        "Paste.ee": "https://paste.ee/u/{}",
        "Rentry.co": "https://rentry.co/{}",
        "ControlC": "https://controlc.com/{}",
        "Ghostbin": "https://ghostbin.com/user/{}",
        "4chan (Arquivo de Busca)": "https://archived.moe/search/username/{}/",
        "8kun (Arquivo)": "https://8kun.top/search?q={}",
        "FreeHack (Fórum)": "https://free-hack.com/member.php?username={}",
        "Viper (Fórum)": "https://viper.top/members/{}/",
        "HashForums": "https://hashforums.co/User-{}",
        "GreySec": "https://greysec.net/member.php?action=profile&uid={}",
        "Offensive Community": "https://offensive.community/user/{}",
        "Breached (Mirror/V2)": "https://breached.vc/User-{}",
        "CyborgForums": "https://cyborgforums.org/User-{}",
        "Vynixu (Hubs)": "https://vynixu.com/users/{}",
        "Rolimons": "https://www.rolimons.com/player/{}",
        "LabyMod": "https://www.labymod.net/profile/{}",
        "Rockstar": "https://socialclub.rockstargames.com/member/{}/",
        "Cracking.org": "https://cracking.org/members/{}/",
        "Wjunction (Webmasters)": "https://www.wjunction.com/members/{}/",
        "Forum.antichat (Rússia)": "https://forum.antichat.com/members/{}/",
        "Social-Engineering.club": "https://social-engineering.club/members/{}/",
        "HackTool.co": "https://hacktool.co/members/{}/",
        "Leak.sx": "https://leak.sx/User-{}",
        "Arios.cc": "https://arios.cc/members/{}/",
        "V3rmillion (Roblox/Lua)": "https://v3rmillion.net/member.php?action=profile&username={}",
        "WeAreDevs": "https://forum.wearedevs.net/profile?uid={}",
        "CheatGlobal": "https://cheatglobal.com/members/{}/",
        "Docker Hub": "https://hub.docker.com/u/{}",
        "NPM JS": "https://www.npmjs.com/~{}",
        "Packagist (PHP)": "https://packagist.org/users/{}/",
        "Crates.io (Rust)": "https://crates.io/users/{}",
        "RubyGems": "https://rubygems.org/profiles/{}",
        "Gogs": "https://gogs.io/{}",
        "SourceGraph": "https://sourcegraph.com/github.com/{}",
        "Dev.to": "https://dev.to/{}",
        "Hashnode": "https://hashnode.com/@{}",
        "Tracker.gg (Fortnite)": "https://fortnitetracker.com/profile/all/{}",
        "Tracker.gg (Apex)": "https://apex.tracker.gg/apex/profile/psn/{}/overview",
        "Rocket League Tracker": "https://rocketleague.tracker.network/rocket-league/profile/steam/{}/overview",
        "LolProfile": "https://lolprofile.net/summoner/br/{}",
        "Tibia.com": "https://www.tibia.com/community/?subtopic=characters&name={}",
        "Hypixel (Minecraft)": "https://hypixel.net/player/{}",
        "2b2t (Stats)": "https://2b2t.online/player/{}",
        "Faceit": "https://www.faceit.com/en/players/{}",
        "Guilded.gg": "https://www.guilded.gg/profile/{}",
        "Filmow (Filmes BR)": "https://filmow.com/usuario/{}",
        "Interpals (Idiomas)": "https://www.interpals.net/{}",
        "Ameba (Japão)": "https://profile.ameba.jp/ameba/{}",
        "Skyrock": "https://{}.skyrock.com/",
        "Fiverr": "https://www.fiverr.com/{}",
        "Upwork": "https://www.upwork.com/freelancers/~{}",
        "99Freelas": "https://www.99freelas.com.br/{}",
        "Guru": "https://www.guru.com/freelancers/{}",
                "Kick": "https://kick.com/{}",
                "Odysee": "https://odysee.com/@{}", 
        "Fansly": "https://fansly.com/{}",
        "Buy Me a Coffee": "https://www.buymeacoffee.com/{}",
        "Patreon (User)": "https://www.patreon.com/user?u={}",
             "Passei Direto": "https://www.passeidireto.com/perfil/{}/",
        "Brainly BR": "https://brainly.com.br/perfil/{}",
        "Quizlet": "https://quizlet.com/{}",
        "Memrise": "https://www.memrise.com/user/{}/",
                "Codeforces": "https://codeforces.com/profile/{}",
        "TopCoder": "https://www.topcoder.com/members/{}",
        "Gitea": "https://gitea.com/{}",
        "Launchpad": "https://launchpad.net/~{}",
        "Cisco Learning": "https://learningnetwork.cisco.com/s/profile/{}",
                "Portal do Gamer": "https://portaldogamer.com.br/members/{}/",
        "GamesBoard BR": "https://gamesboard.com.br/profile/{}/",
        "Tibia Characters": "https://www.tibia.com/community/?subtopic=characters&name={}",
        "Vortex": "https://vortex.gg/user/{}",
        "E-Sport Tracker": "https://est.gg/player/{}",
                "Foundation": "https://foundation.app/@{}",
        "Zapper": "https://zapper.fi/bundle/{}",
        "Tally": "https://www.tally.xyz/profile/{}",
        "Investing.com": "https://www.investing.com/members/{}",
            "CTF-Time": "https://ctftime.org/team/{}",
        "Pentest.WS": "https://pentest.ws/users/{}",
        "Monkeytype": "https://monkeytype.com/profile/{}",
        "Crowdin (Tradução)": "https://crowdin.com/profile/{}",
        "Ludum Dare": "https://ldjam.com/users/{}",
        "SourceHut": "https://sr.ht/~{}/",
        "Buzzer BR": "https://buzzer.com.br/perfil/{}",
        "GamesBoard": "https://gamesboard.com.br/profile/{}/",
        "Scryfall (Magic/TCG)": "https://scryfall.@{}",
        "Letterboxd (Filmes)": "https://letterboxd.com/{}/",
        "Mastodon.Social": "https://mastodon.social/@{}",
        "Farcaster (Warpcast)": "https://warpcast.com/{}",
               "Tinder": "https://tinder.com/@{}",
        "Clubhouse": "https://www.clubhouse.com/@{}",
        "BeReal": "https://bere.al/{}",
        "PayPal.me": "https://www.paypal.com/paypalme/{}",
        "CashApp": "https://cash.app/${}",
        "Venmo": "https://venmo.com/u/{}",
        "Signal (Username)": "https://signal.me/#p/{}",
        "Notion (Public)": "https://{}.notion.site",
        "Jimdo": "https://{}.jimdosite.com/",
        "Webnode": "https://{}.webnode.com/",
        "Milkshake": "https://{}.msha.ke",
        "Linky.bio": "https://linky.bio/{}",
        "Joy.link": "https://joy.link/{}",
        "Bio.fm": "https://bio.fm/{}",
        "Showwcase": "https://www.showwcase.com/{}",
        "MuckRack": "https://muckrack.com/{}",
        "Webflow": "https://webflow.com/{}",
        "Hackerrank": "https://www.hackerrank.com/profile/{}",
        "Freelancer.com": "https://www.freelancer.com/u/{}",
        "PeoplePerHour": "https://www.peopleperhour.com/freelancer/{}",
        "ResearchGate": "https://www.researchgate.net/profile/{}",
        "Academia.edu": "https://independent.academia.edu/{}",
        "Google Scholar": "https://scholar.google.com/citations?user={}",
        "ORCID": "https://orcid.org/{}",
        "OSF (Open Science)": "https://osf.io/{}",
        "EVE Who": "https://evewho.com/character/{}",
        "OSRS HiScores": "https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal.ws?user1={}",
        "FFLogs": "https://www.fflogs.com/character/id/{}",
        "WoWProgress": "https://www.wowprogress.com/character/us/{}",
        "Raider.io": "https://raider.io/characters/us/{}",
        "HLTV (Player)": "https://www.hltv.org/player/{}/",
        "Liquipedia": "https://liquipedia.net/counterstrike/User:{}",
        "Overbuff": "https://www.overbuff.com/players/pc/{}",
        "Dotabuff": "https://www.dotabuff.com/players/{}",
        "Tabstats (R6)": "https://tabstats.com/siege/player/{}",
        "Battlelog (BF4)": "https://battlelog.battlefield.com/bf4/user/{}/",
        "Exophase": "https://www.exophase.com/user/{}/",
        "PsnProfiles": "https://psnprofiles.com/{}",
        "TrueAchievements": "https://www.trueachievements.com/gamer/{}",
        "Nintendo Life": "https://www.nintendolife.com/users/{}",
        "Push Square": "https://www.pushsquare.com/users/{}",
        "Pure Xbox": "https://www.purexbox.com/users/{}",   
        "GameSpot": "https://www.gamespot.com/profile/{}/",
        "IGN Profiles": "https://www.ign.com/person/{}",
        "Kotaku Authors": "https://kotaku.com/author/{}",
        "Polygon Authors": "https://www.polygon.com/authors/{}",
        "The Verge Authors": "https://www.theverge.com/authors/{}",
        "Epic Games Store": "https://store.epicgames.com/u/{}",
        "CdKeys": "https://www.cdkeys.com/user/{}",
        "Wowhead": "https://www.wowhead.com/user={}",
        "Icy Veins": "https://www.icy-veins.com/forums/profile/{}-",
        "Phaver": "https://phaver.com/user/{}",
        "Snapshot": "https://snapshot.org/#/profile/{}",
        "LooksRare": "https://looksrare.org/profile/{}",
        "MagicEden": "https://magiceden.io/u/{}",
        "PolygonScan": "https://polygonscan.com/address/{}",
        "BscScan": "https://bscscan.com/address/{}",
                "Minds": "https://www.minds.com/{}",
        "Gettr": "https://gettr.com/user/{}",
        "Post.news": "https://post.news/@{}",
        "Cohost": "https://cohost.org/{}",
        "CounterSocial": "https://counter.social/@{}",
        "Direct.me": "https://direct.me/{}",
        "Mainstack": "https://mainstack.me/{}",
        "Snipfeed": "https://snipfeed.co/{}",
        "Stan.store": "https://stan.store/{}",
        "Pensight": "https://pensight.com/x/{}",
        "SleekBio": "https://sleek.bio/{}",
        "Bio.site": "https://bio.site/{}",
        "Link.gallery": "https://link.gallery/{}",
        "Zaap.ai": "https://zaap.ai/{}",
        "Tap My Bio": "https://tapmybio.me/{}",
        "Uni.link": "https://uni.link/{}",
        "NGL": "https://ngl.link/{}",
        "ThisCrush": "https://www.thiscrush.com/~{}",
        "Sendit": "https://getsendit.com/u/{}",
        "F3": "https://f3.cool/{}/",
        "Secret Message": "https://secretmessage.link/g/{}",
        "Inkitt": "https://www.inkitt.com/{}",
        "Royal Road": "https://www.royalroad.com/profile/{}",
        "Scribble Hub": "https://www.scribblehub.com/profile/{}/",
        "Webnovel": "https://www.webnovel.com/profile/{}",
        "Tapas.io": "https://tapas.io/{}",
        "Webtoon": "https://www.webtoon.com/en/creator/{}",
        "Calameo": "https://www.calameo.com/accounts/{}",
        "MagCloud": "https://www.magcloud.com/user/{}",
        "Blurb": "https://www.blurb.com/user/{}",
        "Layers.to": "https://layers.to/{}",
        "Peerlist": "https://peerlist.io/{}",
        "Showwcase": "https://www.showwcase.com/{}",
        "Passion.io": "https://{}.passion.io",
        "Toptal": "https://www.toptal.com/resume/{}",
        "Civitai (IA)": "https://civitai.com/user/{}",
        "Destiny Tracker": "https://destinytracker.com/destiny-2/profile/bungie/{}/overview",
        "Halo Tracker": "https://halotracker.com/halo-infinite/profile/xbl/{}/overview",
        "Battlefield Tracker": "https://battlefieldtracker.com/bf1/profile/pc/{}",
        "Robohash (Avatar)": "https://robohash.org/{}",
               "VK (Vkontakte)": "https://vk.com/{}",
        "OK.ru (Odnoklassniki)": "https://ok.ru/{}",
        "LiveJournal": "https://{}.livejournal.com",
        "Rutube": "https://rutube.ru/u/{}",
        "Pikabu": "https://pikabu.ru/@{}",
        "Weibo": "https://weibo.com/{}",
        "Zhihu": "https://www.zhihu.com/people/{}",
        "Douban": "https://www.douban.com/people/{}",
        "Bilibili": "https://space.bilibili.com/{}",
        "Gitee (Dev China)": "https://gitee.com/{}",
        "Taringa (Latam)": "https://www.taringa.net/{}",
        "Xing (Europa)": "https://www.xing.com/profile/{}",
             "Bugcrowd": "https://bugcrowd.com/{}",
        "Keybase": "https://keybase.io/{}",
        "CTFlearn": "https://ctflearn.com/user/{}",
        "RootMe": "https://www.root-me.org/{}",
        "Pypi": "https://pypi.org/user/{}",
        "NPMjs": "https://www.npmjs.com/~{}",
        "Packagist": "https://packagist.org/users/{}/",
        "Canny.io": "https://{}.canny.io",
                "ArtStation": "https://www.artstation.com/{}",
        "DeviantArt": "https://www.deviantart.com/{}",
        "Behance": "https://www.behance.net/{}",
        "Dribbble": "https://dribbble.com/{}",
        "Flickr": "https://www.flickr.com/photos/{}",
        "500px": "https://500px.com/p/{}",
        "VSCO": "https://vsco.co/{}",
        "Houzz": "https://www.houzz.com/user/{}",
        "Pexels": "https://www.pexels.com/@{}",
        "Unsplash": "https://unsplash.com/@{}",
                "Mixcloud": "https://www.mixcloud.com/{}",
        "Last.fm": "https://www.last.fm/user/{}",
        "Bandcamp": "https://bandcamp.com/{}",
        "ReverbNation": "https://www.reverbnation.com/{}",
        "Discogs": "https://www.discogs.com/user/{}",
        "Audiomack": "https://audiomack.com/{}",
        "Chess.com": "https://www.chess.com/member/{}",
        "Lichess": "https://lichess.org/@{}",
        "Letterboxd": "https://letterboxd.com/{}",
        "Goodreads": "https://www.goodreads.com/{}",
        "MyAnimeList": "https://myanimelist.net/profile/{}",
                "Mastodon.social": "https://mastodon.social/@{}",
        "Mastodon.technology": "https://mastodon.technology/@{}",
        "Mastodon.online": "https://mastodon.online/@{}",
        "Pawoo.net": "https://pawoo.net/@{}",
        "Fosstodon": "https://fosstodon.org/@{}",
        "Libre.video": "https://libre.video/u/{}",
        "PeerTube": "https://peertube.otter.sh/u/{}",
               "BuyMeACoffee": "https://www.buymeacoffee.com/{}",
        "Gumroad": "https://{}.gumroad.com",
        "Patreon": "https://www.patreon.com/{}",
        "Substack": "https://{}.substack.com",
        "Vimeo": "https://vimeo.com/{}",
        "Rumble": "https://rumble.com/user/{}",
        "Bitchute": "https://www.bitchute.com/channel/{}",
        "DailyMotion": "https://www.dailymotion.com/{}",
        "ProductHunt": "https://www.producthunt.com/@{}",
        "AngelList": "https://angel.co/u/{}",
                "AllRecipes": "https://www.allrecipes.com/cook/{}",
        "Cookpad": "https://cookpad.com/br/perfil/{}",
        "TudoGostoso": "https://www.tudogostoso.com.br/perfil/{}",
        "Pinterest": "https://www.pinterest.com/{}",
        "Houzz": "https://www.houzz.com.br/user/{}",
        "Apartment Therapy": "https://www.apartmenttherapy.com/authors/{}",
        "Food52": "https://food52.com/users/{}",
        "Zillow": "https://www.zillow.com/profile/{}",
                "Dogster": "https://www.dogster.com/author/{}",
        "Catster": "https://www.catster.com/author/{}",
        "Fishlore": "https://www.fishlore.com/fishforum/members/{}/",
        "HamsterHideout": "http://hamsterhideout.com/forum/user/{}/",
        "BirdForum": "https://www.birdforum.net/members/{}/",
                "Strava": "https://www.strava.com/athletes/{}",
        "Nike Run Club": "https://www.nike.com/u/{}",
        "Garmin Connect": "https://connect.garmin.com/modern/profile/{}",
        "Bodybuilding.com": "https://bodyspace.bodybuilding.com/{}",
        "MyFitnessPal": "https://www.myfitnesspal.com/profile/{}",
        "Pinkbike": "https://www.pinkbike.com/u/{}/",
        "AllTrails": "https://www.alltrails.com/members/{}",
             "Memrise": "https://www.memrise.com/user/{}/",
        "Busuu": "https://www.busuu.com/en/p/{}",
        "Goodreads": "https://www.goodreads.com/user/show/{}",
        "LibraryThing": "https://www.librarything.com/profile/{}",
        "Wattpad": "https://www.wattpad.com/user/{}",
        "Scribd": "https://www.scribd.com/user/{}",
        "Quizlet": "https://quizlet.com/{}",
                "Quora": "https://www.quora.com/profile/{}",
        "Disqus": "https://disqus.com/by/{}",
        "Kiwi6": "https://kiwi6.com/artists/{}",
        "Imgur": "https://imgur.com/user/{}",
        "Gfycat": "https://gfycat.com/@{}",
        "Tenor": "https://tenor.com/users/{}",
        "Flashback.org": "https://www.flashback.org/u{}",
                "PCPartPicker": "https://pcpartpicker.com/user/{}",
        "Tom's Hardware": "https://forums.tomshardware.com/members/{}/",
        "Overclock.net": "https://www.overclock.net/members/{}/",
        "GameFAQS": "https://gamefaqs.gamespot.com/community/{}",
        "Newegg": "https://www.newegg.com/mans-info/{}",
        "BoardGameGeek": "https://boardgamegeek.com/user/{}",
                "TripAdvisor": "https://www.tripadvisor.com.br/Profile/{}",
        "Couchsurfing": "https://www.couchsurfing.com/people/{}",
        "AirBnB": "https://www.airbnb.com.br/users/show/{}",
        "LonelyPlanet": "https://www.lonelyplanet.com/profiles/{}",
                "Udemy": "https://www.udemy.com/user/{}",
        "Skillshare": "https://www.skillshare.com/user/{}",
        "Coursera": "https://www.coursera.org/user/{}",
        "Khan Academy": "https://www.khanacademy.org/profile/{}",
        "Codecademy": "https://www.codecademy.com/profiles/{}",
        "Pluralsight": "https://app.pluralsight.com/profile/{}",
        "EdX": "https://www.edx.org/user/{}",
        "SoloLearn": "https://www.sololearn.com/profile/{}",
        "FreeCodeCamp": "https://www.freecodecamp.org/{}",
                "Figma": "https://www.figma.com/@{}",
        "Adobe Portfolio": "https://{}.myportfolio.com",
        "Carbonmade": "https://{}.carbonmade.com",
        "Coroflot": "https://www.coroflot.com/{}",
        "Contently": "https://{}.contently.com",
        "Crevado": "https://{}.crevado.com",
                "Anchor (Spotify)": "https://anchor.fm/{}",
        "Podbean": "https://{}.podbean.com",
        "Buzzsprout": "https://{}.buzzsprout.com",
        "Spreaker": "https://www.spreaker.com/user/{}",
        "Player.fm": "https://player.fm/{}",
        "ListenNotes": "https://www.listennotes.com/profile/{}",
                "Eventbrite": "https://www.eventbrite.com/o/{}",
        "Meetup": "https://www.meetup.com/members/{}",
        "Sympla": "https://www.sympla.com.br/{}",
        "Luma": "https://lu.ma/{}",
        "Peatix": "https://peatix.com/user/{}",
                "Vercel": "https://vercel.com/{}",
        "Netlify": "https://app.netlify.com/teams/{}/overview",
        "Hashnode": "https://hashnode.com/@{}",
        "Dev.to": "https://dev.to/{}",
        "SourceForge": "https://sourceforge.net/u/{}/profile",
        "Glitch": "https://glitch.com/@{}",
        "CodePen": "https://codepen.io/{}",
        "JSFiddle": "https://jsfiddle.net/user/{}/",
        "Repl.it": "https://replit.com/@{}",
                "Etsy": "https://www.etsy.com/people/{}",
        "ProductHunt": "https://www.producthunt.com/@{}",
        "Trustpilot": "https://www.trustpilot.com/users/{}",
        "eBay": "https://www.ebay.com/usr/{}",
        "Gumroad": "https://{}.gumroad.com",
                "Trello": "https://trello.com/{}",
        "SlideShare": "https://www.slideshare.com/{}",
        "Prezi": "https://prezi.com/user/{}",
        "Miro": "https://miro.com/app/board/{}",
        "Lucidchart": "https://lucid.app/users/profile/{}",
        "Giphy": "https://giphy.com/channel/{}",
        "ImgSrc": "https://imgsrc.ru/main/user.php?user={}",
                "SkyscraperCity": "https://www.skyscrapercity.com/members/{}/",
        "AVS Forum": "https://www.avsforum.com/members/{}/",
        "Bodybuilding": "https://forums.bodybuilding.com/member.php?username={}",
        "Ultimate Guitar": "https://www.ultimate-guitar.com/u/{}",
        "Kaskus": "https://www.kaskus.co.id/@{}",
        "Warrior Forum": "https://www.warriorforum.com/members/{}.html",
        "FlyerTalk": "https://www.flyertalk.com/forum/members/{}.html",
                "Write.as": "https://write.as/{}",
        "Ghost": "https://{}.ghost.io",
        "Wix": "https://{}.wixsite.com",
        "Weebly": "https://{}.weebly.com",
        "Jimdo": "https://{}.jimdosite.com",
        "Postach.io": "https://{}.postach.io",
                "Crunchbase": "https://www.crunchbase.com/person/{}",
        "About.me": "https://about.me/{}",
        "VisualCV": "https://www.visualcv.com/{}",
        "Polywork": "https://www.polywork.com/{}",
        "Contra": "https://contra.com/{}",
                "RetroAchievements": "https://retroachievements.org/user/{}",
        "GameJolt": "https://gamejolt.com/@{}",
        "Itch.io": "https://{}.itch.io",
                "Couchsurfing": "https://www.couchsurfing.com/people/{}",
        "Gaymer": "https://gaymer.org/member.php?username={}",
        "Furaffinity": "https://www.furaffinity.net/user/{}",
        "Keybase": "https://keybase.io/{}",
        "OpenStreetMap": "https://www.openstreetmap.org/user/{}",
        "WikiHow": "https://www.wikihow.com/User:{}",
        "Fandom": "https://www.fandom.com/u/{}",
             "Archive of Our Own (AO3)": "https://archiveofourown.org/users/{}",
        "Fanfiction.net": "https://www.fanfiction.net/u/{}",
        "MangaUpdates": "https://www.mangaupdates.com/members.html?id={}",
        "Anime-Planet": "https://www.anime-planet.com/users/{}",
        "AniList": "https://anilist.co/user/{}",
        "Kitsu": "https://kitsu.io/users/{}",
        "Keybase.io": "https://keybase.io/{}",
        "OpenPGP Key Server": "https://keys.openpgp.org/search?q={}",
        "Onion.link (Proxy)": "https://{}.onion.link",
        "BugMeNot": "http://bugmenot.com/view/{}",
        "Lookbook.nu": "https://lookbook.nu/{}",
        "Vinted": "https://www.vinted.com/member/{}",
        "Grailed": "https://www.grailed.com/{}",
        "Depop": "https://www.depop.com/{}",
        "Zillow (Agent)": "https://www.zillow.com/profile/{}",
        "Realtor.com": "https://www.realtor.com/realestateagents/{}",
        "XDA Developers": "https://forum.xda-developers.com/m/{}/",
        "MacRumors": "https://forums.macrumors.com/members/{}/",
        "DigitalSpy": "https://forums.digitalspy.com/profile/{}",
        "Mumsnet": "https://www.mumsnet.com/Talk/profile/{}",
        "PistonHeads": "https://www.pistonheads.com/gassing/profile.asp?memberId={}",
        "OnlyFans": "https://onlyfans.com/{}",
        "Fansly": "https://fansly.com/{}",
        "ModelMayhem": "https://www.modelmayhem.com/{}",
        "LeetCode": "https://leetcode.com/{}",
        "Cisco Learning": "https://learningnetwork.cisco.com/s/profile/{}",
        "Exercism": "https://exercism.org/profiles/{}",
        "Wikiloc": "https://www.wikiloc.com/wikiloc/user.do?id={}",
        "Komoot": "https://www.komoot.com/user/{}",
        "Geocaching": "https://www.geocaching.com/p/default.aspx?u={}",
        "Mirror.xyz": "https://mirror.xyz/{}",
        "Paragraph.xyz": "https://paragraph.xyz/@{}",
    }

    usos = 0
    
    while True:
        os.system('clear' if os.name == 'posix' else 'cls')
        
        logo = r"""
  ____  ____ _____    ___  ____ ___ _   _ _____
 / ___||  _ \_   _|  / _ \/ ___|_ _| \ | |_   _|
 \___ \| |_) || |   | | | \___ \| ||  \| | | | 
  ___) |  _ < | |   | |_| |___) | || |\  | | | 
 |____/|_| \_\|_|    \___/|____/___|_| \_| |_| 
        """
        print(f"{CY}{logo}{W}")
        print(f"        BY RH")
        print(f"        Digite {R}'88'{W} para desligar o Osint.\n")

        if usos >= 3:
            print(f"{R}[!] Limite de usos atingido, Aguarde 5 segundos.{W}")
            await asyncio.sleep(5)
            usos = 0
            os.system('clear' if os.name == 'posix' else 'cls')
            print(f"{CY}{logo}{W}")
            print(f"        BY RH, STREEX AND TZ\n")

        username = input(f"{G}Digite o Nickname/User do alvo: {W}").strip()
        
        if not username: 
            continue
        if username.lower() == '88':
            print(f"{R}\n[!] Desligando o Osint.{W}")
            break

        sem = asyncio.Semaphore(50)

        async with aiohttp.ClientSession() as session:
            print(f"\n{CY}[!] Conectando ao banco do sherlock.{W}")
            url_db = "https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock_project/resources/data.json"
            
            try:
                async with session.get(url_db, timeout=10) as resp:
                    db_sherlock = await resp.json(content_type=None)
            except Exception as e:
                print(f"{R}[!] Erro ao usar banco do sherlock {e}, Usando banco local.{W}")
                db_sherlock = {}

            total_db = {nome: info['url'] for nome, info in db_sherlock.items() if 'url' in info}
            total_db.update(banco_osint)

            print(f"[*] Procurando {len(total_db)} plataformas para: {G}{username}{W}\n")
            print("=" * 60)

            inicio = time.time()
            encontrados = []
            
            tarefas = [asyncio.create_task(verificar_site(session, n, u, username, encontrados, sem)) for n, u in total_db.items()]
            
            await asyncio.gather(*tarefas)
            
            if encontrados:
                filename = f"resultado_{username}.txt"
                with open(filename, "w") as f:
                    f.write(f"Osint para: {username}\n")
                    f.write("="*30 + "\n")
                    for link in encontrados:
                        f.write(f"{link}\n")
                print(f"\n{G}[!] Resultados salvos em: {filename}{W}")

            fim = time.time()
            print("=" * 60)
            print(f"{CY}[*] Osint finalizado em {fim - inicio:.2f} segundos.{W}")
            print(f"[*] O username foi detectado em {len(encontrados)} plataformas.")
            print("=" * 60)
            
            usos += 1
            
            input(f"\n{CY}[!] Pressione ENTER para voltar ao menu.{W}")

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print(f"\n{R}[!] Osint cancelado.{W}")
